Matrices

In [1]:
import numpy as np

In [6]:
np.random.seed(1)
np.random.randint(1,21,size=15)

array([ 6, 12, 13,  9, 10, 12,  6, 16,  1, 17,  2, 13,  8, 14,  7])

In [11]:

L= [i for i in np.random.randint(1,21,size=40) if i%2==0 ]
L.sort()
L

[2, 2, 6, 6, 8, 8, 8, 8, 8, 8, 10, 10, 14, 14, 14, 16, 18, 18, 20]

In [13]:
L.pop(3)

6

In [47]:
L_arreglo=np.array(L)
L_arreglo

array([ 2,  2,  6,  8,  8,  8,  8,  8,  8, 10, 10, 14, 14, 14, 16, 18, 18])

In [48]:
len(L_arreglo)

17

In [51]:
L_matriz = L_arreglo.reshape(17,1)
L_matriz

array([[ 2],
       [ 2],
       [ 6],
       [ 8],
       [ 8],
       [ 8],
       [ 8],
       [ 8],
       [ 8],
       [10],
       [10],
       [14],
       [14],
       [14],
       [16],
       [18],
       [18]])

In [54]:
M_matriz=np.array([2,3,1,4,5,3,8,3,7,0,12,14,25,26,23,28,89,]).reshape(1,17)
M_matriz

array([[ 2,  3,  1,  4,  5,  3,  8,  3,  7,  0, 12, 14, 25, 26, 23, 28,
        89]])

In [55]:
n= L_matriz @ M_matriz
n

array([[   4,    6,    2,    8,   10,    6,   16,    6,   14,    0,   24,
          28,   50,   52,   46,   56,  178],
       [   4,    6,    2,    8,   10,    6,   16,    6,   14,    0,   24,
          28,   50,   52,   46,   56,  178],
       [  12,   18,    6,   24,   30,   18,   48,   18,   42,    0,   72,
          84,  150,  156,  138,  168,  534],
       [  16,   24,    8,   32,   40,   24,   64,   24,   56,    0,   96,
         112,  200,  208,  184,  224,  712],
       [  16,   24,    8,   32,   40,   24,   64,   24,   56,    0,   96,
         112,  200,  208,  184,  224,  712],
       [  16,   24,    8,   32,   40,   24,   64,   24,   56,    0,   96,
         112,  200,  208,  184,  224,  712],
       [  16,   24,    8,   32,   40,   24,   64,   24,   56,    0,   96,
         112,  200,  208,  184,  224,  712],
       [  16,   24,    8,   32,   40,   24,   64,   24,   56,    0,   96,
         112,  200,  208,  184,  224,  712],
       [  16,   24,    8,   32,   40,   24,   64

In [9]:
L.remove(4)

In [10]:
L+[4]

[16, 8, 10, 8, 6, 20, 16, 16, 8, 20, 2, 18, 14, 4, 14, 12, 8, 14, 12, 12, 4]