Matrices

In [1]:
import numpy as np

In [6]:
np.random.seed(1)
np.random.randint(1,21,size=15)

array([ 6, 12, 13,  9, 10, 12,  6, 16,  1, 17,  2, 13,  8, 14,  7])

In [11]:

L= [i for i in np.random.randint(1,21,size=40) if i%2==0 ]
L.sort()
L

[2, 2, 6, 6, 8, 8, 8, 8, 8, 8, 10, 10, 14, 14, 14, 16, 18, 18, 20]

In [13]:
L.pop(3)

6

In [14]:
L_arreglo=np.array(L)
L_arreglo

array([ 2,  2,  6,  8,  8,  8,  8,  8,  8, 10, 10, 14, 14, 14, 16, 18, 18])

In [18]:
from os import remove


In [22]:
len(L_arreglo)

17

In [19]:
L_arreglo.reshape(17,1)

array([[ 2],
       [ 2],
       [ 6],
       [ 8],
       [ 8],
       [ 8],
       [ 8],
       [ 8],
       [ 8],
       [10],
       [10],
       [14],
       [14],
       [14],
       [16],
       [18],
       [18]])

In [27]:
M_matriz=np.array([2,3,14,19,13,0,2,25,6,9]).reshape(5,2)
M_matriz

array([[ 2,  3],
       [14, 19],
       [13,  0],
       [ 2, 25],
       [ 6,  9]])

In [25]:
L_matriz @ M_matiz

NameError: name 'L_matriz' is not defined

In [9]:
L.remove(4)

In [10]:
L+[4]

[16, 8, 10, 8, 6, 20, 16, 16, 8, 20, 2, 18, 14, 4, 14, 12, 8, 14, 12, 12, 4]